In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#### Accuracy



$Accuracy$ = $Number of correct prediction / Total number of predictions$

In [16]:
y = np.array(["cat","dog","cat","cat"])
yhat = np.array(["cat","dog","cat","dog"])

In [17]:
from sklearn.metrics import accuracy_score

In [18]:
accuracy_score(y,yhat)*100

75.0

In [19]:
a = np.array(["male","female","male","female","male"])
ab = np.array(["male","male","female","female","male"])

In [20]:
accuracy_score(a,ab)*100

60.0

#### Multiclass averaging

In [21]:
x = np.array(["cat","dog","foosa","cat"])
xhat = np.array(["cat","dog","cat","dog"])

In [22]:
from sklearn.metrics import precision_score

In [23]:
precision_score(x,xhat,average="micro")*100

50.0

In [24]:
precision_score(x,xhat,average="macro")*100

c:\users\91833\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


33.33333333333333

In [25]:
from sklearn import metrics
y_true = [0,1,2,0,1,2] # 3 labels
y_pred = [0,2,1,0,0,1]

In [26]:
metrics.precision_score(y_true,y_pred,average="macro")

0.2222222222222222

In [27]:
metrics.recall_score(y_true,y_pred,average="micro")

0.3333333333333333

In [28]:
metrics.f1_score(y_true,y_pred,average='weighted')

0.26666666666666666

In [29]:
metrics.fbeta_score(y_true,y_pred,average='macro',beta=0.5)

0.23809523809523805

In [30]:
metrics.precision_recall_fscore_support(y_true,y_pred,beta=0.5,average=None)

(array([0.66666667, 0.        , 0.        ]),
 array([1., 0., 0.]),
 array([0.71428571, 0.        , 0.        ]),
 array([2, 2, 2], dtype=int64))

In [31]:
metrics.recall_score(y_true,y_pred,labels=[1,2],average="micro")

0.0

In [32]:
metrics.precision_score(y_true,y_pred,labels=[0,1,2,3],average='macro')

0.16666666666666666

#### Confusion Matrix

In [33]:
actual = np.array([1,1,1,1,1,1,1,1,0,0,0,0,0])
prediction = np.array([0,0,0,1,1,1,1,1,0,0,0,1,1])

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
cm = confusion_matrix(actual,prediction)

In [36]:
cm

array([[3, 2],
       [3, 5]], dtype=int64)

In [37]:
y = np.array(["cat","dog","cat","cat"])
yhat = np.array(["cat","dog","cat","dog"])

In [38]:
cm1 = confusion_matrix(y,yhat)

In [39]:
cm1

array([[2, 1],
       [0, 1]], dtype=int64)

In [40]:
data = pd.read_csv("https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Classification/Breast%20cancer%20wisconsin.csv")

In [41]:
data

Unnamed: 0        id diagnosis  radius_mean  texture_mean  \
0             0    842302         M        17.99         10.38   
1             1    842517         M        20.57         17.77   
2             2  84300903         M        19.69         21.25   
3             3  84348301         M        11.42         20.38   
4             4  84358402         M        20.29         14.34   
..          ...       ...       ...          ...           ...   
564         564    926424         M        21.56         22.39   
565         565    926682         M        20.13         28.25   
566         566    926954         M        16.60         28.08   
567         567    927241         M        20.60         29.33   
568         568     92751         B         7.76         24.54   

     perimeter_mean  area_mean  smoothness_mean  compactness_mean  \
0            122.80     1001.0          0.11840           0.27760   
1            132.90     1326.0          0.08474           0.07864   
2            130.00     1203.0          0.10960           0.15990   
3             77.58      386.1          0.14250           0.28390   
4            135.10     1297.0          0.10030           0.13280   
..              ...        ...              ...               ...   
564          142.00     1479.0          0.11100           0.11590   
565          131.20     1261.0          0.09780           0.10340   
566          108.30      858.1          0.08455           0.10230   
567          140.10     1265.0          0.11780           0.27700   
568           47.92      181.0          0.05263           0.04362   

     concavity_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.30010  ...        25.380          17.33           184.60   
1           0.08690  ...        24.990          23.41           158.80   
2           0.19740  ...        23.570          25.53           152.50   
3           0.24140  ...        14.910          26.50            98.87   
4           0.19800  ...        22.540          16.67           152.20   
..              ...  ...           ...            ...              ...   
564         0.24390  ...        25.450          26.40           166.10   
565         0.14400  ...        23.690          38.25           155.00   
566         0.09251  ...        18.980          34.12           126.70   
567         0.35140  ...        25.740          39.42           184.60   
568         0.00000  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216          0.2060                  0.07115  
565                0.1628          0.2572                  0.0663

In [42]:
data.head()

Unnamed: 0        id diagnosis  radius_mean  texture_mean  perimeter_mean  \
0           0    842302         M        17.99         10.38          122.80   
1           1    842517         M        20.57         17.77          132.90   
2           2  84300903         M        19.69         21.25          130.00   
3           3  84348301         M        11.42         20.38           77.58   
4           4  84358402         M        20.29         14.34          135.10   

   area_mean  smoothness_mean  compactness_mean  concavity_mean  ...  \
0     1001.0          0.11840           0.27760          0.3001  ...   
1     1326.0          0.08474           0.07864          0.0869  ...   
2     1203.0          0.10960           0.15990          0.1974  ...   
3      386.1          0.14250           0.28390          0.2414  ...   
4     1297.0          0.10030           0.13280          0.1980  ...   

   radius_worst  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0         25.38          17.33           184.60      2019.0            0.1622   
1         24.99          23.41           158.80      1956.0            0.1238   
2         23.57          25.53           152.50      1709.0            0.1444   
3         14.91          26.50            98.87       567.7            0.2098   
4         22.54          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 33 columns]

In [43]:
data.shape

(569, 33)

In [44]:
data.describe

<bound method NDFrame.describe of      Unnamed: 0        id diagnosis  radius_mean  texture_mean  \
0             0    842302         M        17.99         10.38   
1             1    842517         M        20.57         17.77   
2             2  84300903         M        19.69         21.25   
3             3  84348301         M        11.42         20.38   
4             4  84358402         M        20.29         14.34   
..          ...       ...       ...          ...           ...   
564         564    926424         M        21.56         22.39   
565         565    926682         M        20.13         28.25   
566         566    926954         M        16.60         28.08   
567         567    927241         M        20.60         29.33   
568         568     92751         B         7.76         24.54   

     perimeter_mean  area_mean  smoothness_mean  compactness_mean  \
0            122.80     1001.0          0.11840           0.27760   
1            132.90     1326.0     

In [45]:
data.isnull()

Unnamed: 0     id  diagnosis  radius_mean  texture_mean  perimeter_mean  \
0         False  False      False        False         False           False   
1         False  False      False        False         False           False   
2         False  False      False        False         False           False   
3         False  False      False        False         False           False   
4         False  False      False        False         False           False   
..          ...    ...        ...          ...           ...             ...   
564       False  False      False        False         False           False   
565       False  False      False        False         False           False   
566       False  False      False        False         False           False   
567       False  False      False        False         False           False   
568       False  False      False        False         False           False   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  ...  \
0        False            False             False           False  ...   
1        False            False             False           False  ...   
2        False            False             False           False  ...   
3        False            False             False           False  ...   
4        False            False             False           False  ...   
..         ...              ...               ...             ...  ...   
564      False            False             False           False  ...   
565      False            False             False           False  ...   
566      False            False             False           False  ...   
567      False            False             False           False  ...   
568      False            False             False           False  ...   

     radius_worst  texture_worst  perimeter_worst  area_worst  \
0           False          False            False       False   
1           False          False            False       False   
2           False          False            False       False   
3           False          False            False       False   
4           False          False            False       False   
..            ...            ...              ...         ...   
564         False          False            False       False   
565         False          False            False       False   
566         False          False            False       False   
567         False          False            False       False   
568         False          False            False       False   

     smoothness_worst  compactness_worst  concavity_worst  \
0               False              False            False   
1               False              False            False   
2               False              False            False   
3               False              False            False   
4               False              False            False   
..                ...                ...              ...   
564             False              False            False   
565             False              False            False   
566             False              False            False   
567             False              False            False   
568             False              False            False   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                   False           False                    False  
1                   False           False                    False  
2                   False           False                    False  
3                   False           False                    False  
4                   False           False                    False  
..                    ...             ...                      ...  
564                 False           False                    False  
565                 False           False                    False  
566                 

In [46]:
data.isnull().sum()

Unnamed: 0                 0
id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [47]:
df = data.drop('Unnamed: 0',axis=1)

In [48]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [49]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
l = LabelEncoder()

In [54]:
a = l.fit_transform(df["diagnosis"])

In [55]:
x = df.drop("diagnosis",axis=1)
y = a

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [57]:
from sklearn.neighbors import KNeighborsClassifier

In [58]:
knn = KNeighborsClassifier()

In [59]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [60]:
y_pred = knn.predict(x_test)
y_pred

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [61]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0])

In [62]:
from sklearn.metrics import confusion_matrix

In [63]:
cm2 = confusion_matrix(y_test,y_pred)

In [64]:
cm2

array([[81, 11],
       [22, 29]], dtype=int64)

In [65]:
TP = cm2[0,0]

In [66]:
TP

81

In [67]:
TN = cm2[1,1]

In [68]:
TN

29

In [69]:
FP = cm2[1,0]

In [70]:
FP

22

In [71]:
FN = cm2[0,1]

In [72]:
FN

11

In [85]:
#### True positive rate
TPR = TP/(TP+FN)

In [86]:
TPR

0.8804347826086957

In [87]:
#### True negative rate (TNR)
TNR = TN/(TN+FP)

In [88]:
TNR

0.5686274509803921

In [111]:
#### positive predictive value (PPV)
PPV = TP/(TP+FP)
PPV

0.7864077669902912

In [112]:
#### Negative predictive value (NPV)
NPV = TN/(TN+FN)
NPV

0.725

In [113]:
#### False negative rate (FNR)
FNR = FN/(FN+TP)
FNR

0.11956521739130435

In [114]:
#### False positive rate (FPR)
FPR = FP/(FP+TN)
FPR

0.43137254901960786

In [115]:
#### False discovery rate (FDR)
FDR = FP/(FP+TP)

In [116]:
FDR

0.21359223300970873

In [117]:
#### False omission rate (FOR)
FOR = FN/(FN+TN)
FOR

0.275

In [118]:
#### Prevalence Threshold (PT)
PT = np.sqrt(TPR*(-TNR+1))+TNR-1/(TPR+TNR-1)
PT

-1.041959964644146

In [119]:
#### Threat score or critical success index 
TS = TP/(TP+FN+FP)
TS

0.7105263157894737

In [120]:
#### Accuracy
AC = (TP+TN)/(TP+TN+FP+FN)
AC

0.7692307692307693

In [121]:
## Balanced Accuracy
BA = (TPR+TNR)/2
BA

0.7245311167945439

In [122]:
#### F1 score
F1 = 2*TP/(2*TP+FP+FN)
F1

0.8307692307692308

In [123]:
#### Mathews Correlation Coefficient
MCC = ((TP*TN)-(FP*FN))/np.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
MCC

0.4792221970229133

In [124]:
#### Fowlkes-mallows index
FMI = (np.sqrt(TP/(TP+FP)*(TP/(TP+FN))))
FMI

0.8320941962133175

In [125]:
# Informedness pr bookmaker informedness
IB = TPR+(TNR-1)
IB

0.4490622335890878

In [126]:
# Markedness or Deltap
MK = (PPV+NPV-1)
MK

0.5114077669902912